name: Build and Deploy to Public Repo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Public Repo
        run: |
          cd dist
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from private repo"
          git push --force https://${{ secrets.DEPLOY_TOKEN }}@github.com/kiniv-21/trios-data.git main